version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-inovetix-cms
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inovetix-cms-db
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
